//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASM.DAL.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDetail
    {
        public int ProductDetailI { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string Color { get; set; }
        public string Size { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
