//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASM.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderID { get; set; }
        public int CustomerID { get; set; }
        public int PaymentID { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public System.DateTime RequiredDate { get; set; }
        public Nullable<System.DateTime> ShipDate { get; set; }
        public Nullable<int> ShipperID { get; set; }
        public Nullable<decimal> Freight { get; set; }
        public Nullable<decimal> SalesTax { get; set; }
        public string Timestamp { get; set; }
        public string TransactStatus { get; set; }
        public string ErrLoc { get; set; }
        public string ErrMsg { get; set; }
        public Nullable<bool> Fulfilled { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Payment Payment { get; set; }
        public virtual Shipper Shipper { get; set; }
    }
}
